In [1]:
import os

print(os.getcwd())

/home/dgsetiawan/MachineLearning/ZhongLab/HistoneModificationInterpretation/Data/Matrices

In [2]:
import pandas as pd
import numpy as np

In [3]:
folder_path = "/home/dgsetiawan/MachineLearning/ZhongLab/HistoneModificationInterpretation/Data/Matrices/"

dataframes = []

for file_name in os.listdir(folder_path):
    if file_name.endswith(".mat"):
        file_path = os.path.join(folder_path, file_name)
        print(f"Processing file:{file_name}")

        #Load data
        df = pd.read_csv(file_path, sep="\t", skiprows=1, header=None)

        filtered_df = df[[3,6]]

        filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

        filtered_df.columns = ['ID', os.path.splitext(os.path.basename(file_name))[0]]

        dataframes.append(filtered_df)

merged_df = dataframes[0]
for df in dataframes[1:]:
    merged_df = pd.merge(merged_df, df, on='ID', how='outer')

merged_df

Processing file:H3K27me3.mat
Processing file:H3K9Ac.mat
Processing file:H2A.2.mat
Processing file:H3K4me1.mat

/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

Processing file:cpg_percentage.mat
Processing file:H3K9K14Ac.mat
Processing file:H3K9me2.mat

/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

Processing file:H3Ac.mat
Processing file:H2A.13.mat
Processing file:H3K4me3.mat
Processing file:chh_percentage.mat

/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

Processing file:H4K20me1.mat
Processing file:H3K36me3.mat
Processing file:H4K5Ac.mat
Processing file:chg_percentage.mat

/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

Processing file:H2A.W.7.mat
Processing file:H3K9me1.mat
Processing file:H2A.Z.11.mat
Processing file:H2A.W.6.mat

/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')
/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

Processing file:H2A.Z.9.mat

/tmp/ipykernel_277013/3953230728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[3] = filtered_df[3].str.extract(r'ID=([^;]+)')

,ID,H3K27me3,H3K9Ac,H2A.2,H3K4me1,cpg_percentage,H3K9K14Ac,H3K9me2,H3Ac,H2A.13,...,chh_percentage,H4K20me1,H3K36me3,H4K5Ac,chg_percentage,H2A.W.7,H3K9me1,H2A.Z.11,H2A.W.6,H2A.Z.9
0,AT1G01010,9.555596,21.069372,20.902491,21.780787,4.165791,18.996291,11.649541,66.714715,21.709216,...,0.483944,17.027416,24.658615,20.698356,0.515154,9.485396,15.045602,30.825020,8.652080,31.888816
1,AT1G01020,8.281369,21.901954,23.740520,15.113436,7.429205,25.495332,8.942999,16.714578,19.870964,...,0.376212,9.444864,23.943244,13.163694,0.126655,7.561008,11.451991,13.115434,7.134915,12.818302
2,AT1G01030,78.608479,29.330605,17.747587,15.150620,0.504558,44.084202,7.870447,99.910557,19.173416,...,0.228269,10.814976,21.883899,21.484286,0.027360,8.949513,9.853661,33.601489,7.651782,49.968756
3,AT1G01040,12.855501,13.052602,37.745676,23.522419,63.432333,12.666346,8.761089,39.199217,36.108781,...,0.322490,16.531930,34.021623,20.185070,0.445781,9.908798,14.655745,7.559050,8.830450,5.283599
4,AT1G01046,5.504198,6.469693,41.282402,21.102996,66.785714,4.328157,8.557769,11.054449,29.419700,...,0.000000,13.236156,29.929285,4.927668,0.000000,5.332162,17.590990,3.533677,9.575662,0.448822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28770,ATMG01370,32.689948,38.834714,9.791233,25.818499,6.967064,2.650933,36.760161,59.743526,13.143619,...,1.632489,78.670024,16.924194,62.596490,5.063290,73.292376,52.484612,15.727549,67.290737,2.073800
28771,ATMG01380,29.265119,37.131102,4.064745,26.522141,10.119048,2.439536,23.966020,43.782341,7.263313,...,1.667391,54.342888,17.719710,45.133951,5.610860,63.742126,50.953566,22.696829,69.574059,2.769753
28772,ATMG01390,36.481618,46.825683,10.577389,29.130166,7.056053,4.308867,41.924335,67.083654,13.536770,...,1.195546,76.840660,17.714846,56.131249,3.758958,70.104719,55.221235,17.293007,78.771046,1.759354
28773,ATMG01400,37.483596,62.856792,8.288229,33.713869,11.347190,1.679279,44.856578,62.394773,13.250560,...,1.478729,78.087953,20.086460,57.464894,7.347074,67.996715,59.289039,20.810699,92.272202,2.097277
28774,ATMG01410,39.676169,50.393678,13.961536,36.163759,8.142734,3.442715,46.598579,56.019006,17.812880,...,1.824951,80.866941,20.192139,57.492576,5.892532,61.737140,55.015549,21.013259,89.426007,1.389277

In [4]:
target_df = pd.read_csv("SRR7405039.mat.genes.results", sep="\t")
target_df

,gene_id,transcript_id(s),length,effective_length,expected_count,TPM,FPKM
0,AT1G01010,AT1G01010.1,1688.00,1640.00,429.00,5.48,4.29
1,AT1G01020,"AT1G01020.1,AT1G01020.2",1206.84,1158.84,424.00,7.66,5.99
2,AT1G01030,AT1G01030.1,1905.00,1857.00,650.00,7.33,5.74
3,AT1G01040,"AT1G01040.1,AT1G01040.2",6229.56,6181.56,3392.00,11.49,8.99
4,AT1G01050,AT1G01050.1,976.00,928.00,3784.31,85.42,66.82
...,...,...,...,...,...,...,...
27411,ATMG01350,ATMG01350.1,438.00,390.00,70.00,3.76,2.94
27412,ATMG01360,ATMG01360.1,1584.00,1536.00,14.00,0.19,0.15
27413,ATMG01370,ATMG01370.1,336.00,288.00,94.00,6.84,5.35
27414,ATMG01400,ATMG01400.1,318.00,270.00,5.00,0.39,0.30
27415,ATMG01410,ATMG01410.1,615.00,567.00,11.00,0.41,0.32

In [5]:
target_df = target_df[['gene_id', 'FPKM']]
target_df.columns = ['ID', 'Gene Expression (FPKM)']
target_df

              ID  Gene Expression (FPKM)
0      AT1G01010                    4.29
1      AT1G01020                    5.99
2      AT1G01030                    5.74
3      AT1G01040                    8.99
4      AT1G01050                   66.82
...          ...                     ...
27411  ATMG01350                    2.94
27412  ATMG01360                    0.15
27413  ATMG01370                    5.35
27414  ATMG01400                    0.30
27415  ATMG01410                    0.32

[27416 rows x 2 columns]

In [6]:
merged_df = pd.merge(merged_df, target_df, on='ID', how='inner')
merged_df

,ID,H3K27me3,H3K9Ac,H2A.2,H3K4me1,cpg_percentage,H3K9K14Ac,H3K9me2,H3Ac,H2A.13,...,H4K20me1,H3K36me3,H4K5Ac,chg_percentage,H2A.W.7,H3K9me1,H2A.Z.11,H2A.W.6,H2A.Z.9,Gene Expression (FPKM)
0,AT1G01010,9.555596,21.069372,20.902491,21.780787,4.165791,18.996291,11.649541,66.714715,21.709216,...,17.027416,24.658615,20.698356,0.515154,9.485396,15.045602,30.825020,8.652080,31.888816,4.29
1,AT1G01020,8.281369,21.901954,23.740520,15.113436,7.429205,25.495332,8.942999,16.714578,19.870964,...,9.444864,23.943244,13.163694,0.126655,7.561008,11.451991,13.115434,7.134915,12.818302,5.99
2,AT1G01030,78.608479,29.330605,17.747587,15.150620,0.504558,44.084202,7.870447,99.910557,19.173416,...,10.814976,21.883899,21.484286,0.027360,8.949513,9.853661,33.601489,7.651782,49.968756,5.74
3,AT1G01040,12.855501,13.052602,37.745676,23.522419,63.432333,12.666346,8.761089,39.199217,36.108781,...,16.531930,34.021623,20.185070,0.445781,9.908798,14.655745,7.559050,8.830450,5.283599,8.99
4,AT1G01050,8.769121,19.552223,22.483920,15.337061,12.003940,21.647277,10.418079,23.592821,22.655993,...,9.598756,26.216809,10.410831,0.312506,7.044291,10.411998,15.680742,6.427658,14.057521,66.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27411,ATMG01350,38.778550,38.416176,12.264754,31.436731,6.584528,3.233744,38.137956,69.699428,14.579819,...,77.658056,16.431142,68.265613,3.907698,70.937823,53.521046,16.844936,72.897514,1.136329,2.94
27412,ATMG01360,45.464497,58.675718,13.084067,33.773001,8.285592,4.734936,46.497621,74.641999,17.576241,...,86.107950,21.668732,69.832254,5.451866,73.181999,58.941690,21.115902,89.777369,2.012005,0.15
27413,ATMG01370,32.689948,38.834714,9.791233,25.818499,6.967064,2.650933,36.760161,59.743526,13.143619,...,78.670024,16.924194,62.596490,5.063290,73.292376,52.484612,15.727549,67.290737,2.073800,5.35
27414,ATMG01400,37.483596,62.856792,8.288229,33.713869,11.347190,1.679279,44.856578,62.394773,13.250560,...,78.087953,20.086460,57.464894,7.347074,67.996715,59.289039,20.810699,92.272202,2.097277,0.30
27415,ATMG01410,39.676169,50.393678,13.961536,36.163759,8.142734,3.442715,46.598579,56.019006,17.812880,...,80.866941,20.192139,57.492576,5.892532,61.737140,55.015549,21.013259,89.426007,1.389277,0.32

In [7]:
merged_df.to_csv("Histone_Modification_Characterization.tsv", index=False, sep="\t")